# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [2]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Jian,CN,27.1172,114.9793,65.57,71,58,8.75,broken clouds
1,1,Salima,MW,-13.7804,34.4587,90.37,19,2,3.36,clear sky
2,2,Dikson,RU,73.5069,80.5464,31.33,70,100,5.01,overcast clouds
3,3,Punta Arenas,CL,-53.1500,-70.9167,46.51,61,75,11.50,broken clouds
4,4,Jizan,SA,17.3333,42.6667,92.34,49,43,12.08,scattered clouds

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [3]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [4]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) & 
                                       (city_data_df["Max Temp"] <= max_temp)]
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Pandan,PH,14.0453,124.1694,80.15,87,96,7.74,overcast clouds
7,7,Riberalta,BO,-10.9833,-66.1000,86.20,70,43,4.61,scattered clouds
9,9,Safaga,EG,26.7292,33.9365,87.40,53,8,10.18,clear sky
11,11,Angoche,MZ,-16.2325,39.9086,78.01,74,0,11.59,clear sky
12,12,Cabo San Lucas,MX,22.8909,-109.9124,82.51,73,5,5.91,clear sky
15,15,Sao Filipe,CV,14.8961,-24.4956,80.15,76,57,3.89,broken clouds
18,18,Touros,BR,-5.1989,-35.4608,86.25,58,2,17.85,clear sky
19,19,Vaini,TO,-21.2000,-175.2000,73.56,94,100,4.61,overcast clouds
20,20,Young,UY,-32.6833,-57.6333,71.11,40,59,15.30,broken clouds
21,21,Mundo Nuevo,MX,18.7000,-95.5000,76.55,83,31,4.25,scattered clouds

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [5]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()

# Display sample data
clean_travel_cities

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,Pandan,PH,14.0453,124.1694,80.15,87,96,7.74,overcast clouds
7,7,Riberalta,BO,-10.9833,-66.1000,86.20,70,43,4.61,scattered clouds
9,9,Safaga,EG,26.7292,33.9365,87.40,53,8,10.18,clear sky
11,11,Angoche,MZ,-16.2325,39.9086,78.01,74,0,11.59,clear sky
12,12,Cabo San Lucas,MX,22.8909,-109.9124,82.51,73,5,5.91,clear sky
...,...,...,...,...,...,...,...,...,...,...
698,698,Lujan,AR,-34.5703,-59.1050,71.94,50,97,1.99,overcast clouds
702,702,Kharhial,IN,20.2833,82.7667,77.34,89,16,4.88,few clouds
705,705,Jalu,LY,29.0331,21.5482,87.03,29,0,10.13,clear sky
706,706,Pemba,MZ,-12.9740,40.5178,81.30,65,20,10.36,few clouds
707,707,Alta Floresta,BR,-9.8756,-56.0861,89.42,55,81,4.61,broken clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [19]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = hotel_df = preferred_cities_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Pandan,PH,80.15,overcast clouds,14.0453,124.1694,
7,Riberalta,BO,86.20,scattered clouds,-10.9833,-66.1000,
9,Safaga,EG,87.40,clear sky,26.7292,33.9365,
11,Angoche,MZ,78.01,clear sky,-16.2325,39.9086,
12,Cabo San Lucas,MX,82.51,clear sky,22.8909,-109.9124,
15,Sao Filipe,CV,80.15,broken clouds,14.8961,-24.4956,
18,Touros,BR,86.25,clear sky,-5.1989,-35.4608,
19,Vaini,TO,73.56,overcast clouds,-21.2000,-175.2000,
20,Young,UY,71.11,broken clouds,-32.6833,-57.6333,
21,Mundo Nuevo,MX,76.55,scattered clouds,18.7000,-95.5000,

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [20]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df["Hotel Name"] = ""


# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Pandan,PH,80.15,overcast clouds,14.0453,124.1694,
7,Riberalta,BO,86.20,scattered clouds,-10.9833,-66.1000,
9,Safaga,EG,87.40,clear sky,26.7292,33.9365,
11,Angoche,MZ,78.01,clear sky,-16.2325,39.9086,
12,Cabo San Lucas,MX,82.51,clear sky,22.8909,-109.9124,
15,Sao Filipe,CV,80.15,broken clouds,14.8961,-24.4956,
18,Touros,BR,86.25,clear sky,-5.1989,-35.4608,
19,Vaini,TO,73.56,overcast clouds,-21.2000,-175.2000,
20,Young,UY,71.11,broken clouds,-32.6833,-57.6333,
21,Mundo Nuevo,MX,76.55,scattered clouds,18.7000,-95.5000,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [21]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [22]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [23]:
# Display sample data
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Pandan,PH,80.15,overcast clouds,14.0453,124.1694,Bonifacio Lodge
7,Riberalta,BO,86.20,scattered clouds,-10.9833,-66.1000,Hotel Colonial
9,Safaga,EG,87.40,clear sky,26.7292,33.9365,Lamar Resort Abu Soma
11,Angoche,MZ,78.01,clear sky,-16.2325,39.9086,Guest House HESADA
12,Cabo San Lucas,MX,82.51,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
15,Sao Filipe,CV,80.15,broken clouds,14.8961,-24.4956,Hotel Xaguate
18,Touros,BR,86.25,clear sky,-5.1989,-35.4608,INN NEW HORIZON
19,Vaini,TO,73.56,overcast clouds,-21.2000,-175.2000,Keleti Beach Resort
20,Young,UY,71.11,broken clouds,-32.6833,-57.6333,Posada Gira el Sol
21,Mundo Nuevo,MX,76.55,scattered clouds,18.7000,-95.5000,

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [24]:
# Drop the rows where there is no Hotel Name.
c = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df = c.dropna()

# Display sample data
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,Pandan,PH,80.15,overcast clouds,14.0453,124.1694,Bonifacio Lodge
7,Riberalta,BO,86.20,scattered clouds,-10.9833,-66.1000,Hotel Colonial
9,Safaga,EG,87.40,clear sky,26.7292,33.9365,Lamar Resort Abu Soma
11,Angoche,MZ,78.01,clear sky,-16.2325,39.9086,Guest House HESADA
12,Cabo San Lucas,MX,82.51,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
...,...,...,...,...,...,...,...
314,Waingapu,ID,80.92,moderate rain,-9.6567,120.2641,Pondok Wisata Elim
315,Saint-Joseph,RE,71.98,few clouds,-21.3667,55.6167,"""Plantation Bed and Breakfast"
324,Shimoni,KE,77.92,broken clouds,-4.6476,39.3817,Shimoni Reef Lodge
325,Panambi,BR,77.52,clear sky,-28.2925,-53.5017,Hotel Lages Panambi
329,Cocorit,MX,79.41,clear sky,27.5833,-109.9667,Kaba Motel

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [27]:
 #In case of an empty DataFrame, load the sample data provided
#clean_hotel_df = pd.read_csv("weatherPy_vacation-backup.csv")

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [29]:
# Set the file name.
output_data_file ="weatherpy_vacation.csv"

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [36]:
# Review the formatting template provided
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [31]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n<dl>\n<dt>Hotel Name</dt><dd>Bonifacio Lodge</dd>\n<dt>City</dt><dd>Pandan</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 80.15 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Colonial</dd>\n<dt>City</dt><dd>Riberalta</dd>\n<dt>Country</dt><dd>BO</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 86.2 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Lamar Resort Abu Soma</dd>\n<dt>City</dt><dd>Safaga</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Current Weather</dt><dd>clear sky and 87.4 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Guest House HESADA</dd>\n<dt>City</dt><dd>Angoche</dd>\n<dt>Country</dt><dd>MZ</dd>\n<dt>Current Weather</dt><dd>clear sky and 78.01 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Tesoro Los Cabos</dd>\n<dt>City</dt><dd>Cabo San Lucas</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Current Weather</dt><dd>clear sky and 82.51 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Hotel Xaguate</dd>\n<dt>City</dt><dd>Sao Filipe</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Current Weather</dt><dd>broken clouds and 80.15 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>INN NEW HORIZON</dd>\n<dt>City</dt><dd>Touros</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Current Weather</dt><dd>clear sky and 86.25 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Keleti Beach Resort</dd>\n<dt>City</dt><dd>Vaini</dd>\n<dt>Country</dt><dd>TO</dd>\n<dt>Current Weather</dt><dd>overcast clouds and 73.56 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Posada Gira el Sol</dd>\n<dt>City</dt><dd>Young</dd>\n<dt>Country</dt><dd>UY</dd>\n<dt>Current Weather</dt><dd>broken clouds and 71.11 °F</dd>\n</dl>\n',
 '\n<dl>\n<dt>Hotel Name</dt><dd>Shanti Maurice Resort & Spa</dd>\n<dt>City</dt><dd>Souillac</dd>\n<dt>Country</dt><dd>MU</dd>\n<dt>Current Weather</dt><dd>scattered clouds and 73.78 °F</dd>\n</dl>\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [45]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
6   14.0453  124.1694
7  -10.9833  -66.1000
9   26.7292   33.9365
11 -16.2325   39.9086
12  22.8909 -109.9124
15  14.8961  -24.4956
18  -5.1989  -35.4608
19 -21.2000 -175.2000
20 -32.6833  -57.6333
41 -20.5167   57.5167

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [46]:
# Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Create a figure to add the Google map as a layer
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, dissipating=False, max_intensity=300, point_radius=4)

# Display the figure containing the map
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

fig

Figure(layout=FigureLayout(height='420px'))